Add support for RelayedV2 transactions
multiversx/mx-sdk-py-core pull request #22
Opened 2023-06-12 12:40 UTC by popenta

Added support for RelayedV2 transactions.
Also added unit tests. The tests are the ones from mx-sdk-js-core and can be found [here](https://github.com/multiversx/mx-sdk-js-core/blob/main/src/relayedTransactionV2Builder.spec.ts)

2023-06-13 09:53 UTC, andreibancioiu submitted a review, later dismissed

2023-06-13 10:00 UTC, andreibancioiu submitted a review, later dismissed

2023-06-14 08:30 UTC, bogdan-rosianu requested changes

2023-06-14 08:36 UTC, popenta commented on multiversx_sdk_core/transaction_builders/relayed_v2_builder.py
> +            gas_limit=self.inner_transaction.gas_limit + self.network_config.min_gas_limit + self.network_config.gas_per_data_byte * payload.length(),
Done!

2023-06-14 08:36 UTC, bogdan-rosianu approved these changes

2023-06-14 08:36 UTC, andreibancioiu approved these changes

2023-06-14 08:36 UTC, merged